<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="oida" nsURI="http://net/bauhaus-luftfahrt/oida" nsPrefix="net.bauhaus-luftfahrt.oida">
  <eSubpackages name="ontologyMgr" nsURI="http://net/bauhaus-luftfahrt/oida/ontologyMgr"
      nsPrefix="net.bauhaus-luftfahrt.oida.ontologyMgr">
    <eClassifiers xsi:type="ecore:EClass" name="Library">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="owner" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="creationDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ontologies" upperBound="-1"
          eType="#//ontologyMgr/LocalReferenceOntologyFileSet" containment="true"
          resolveProxies="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="referenceOntology" eType="#//ontologyMgr/LocalReferenceOntologyFileSet"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LocalReferenceOntologyFileSet" eSuperTypes="#//ontologyMgr/OntologyFile">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="maintenanceFileName"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="GitRepoOntologyEntry" eSuperTypes="#//ontologyMgr/LocalReferenceOntologyFileSet">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="repoURL" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="gitUsername" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="gitPassword" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OntologyFile">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="managedOntology" eType="#//ontology/Ontology"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="ontology" nsURI="http://net/bauhaus-luftfahrt/oida/ontology"
      nsPrefix="net.bauhaus-luftfahrt.oida.ontology">
    <eClassifiers xsi:type="ecore:EClass" name="OntologyItem">
      <eStructuralFeatures xsi:type="ecore:EReference" name="containingOntology" eType="#//ontology/Ontology"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="iri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Ontology" eSuperTypes="#//ontology/OntologyItem">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="namespaces" upperBound="-1"
          eType="#//ontology/OntologyNamespace" containment="true" resolveProxies="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
          eType="#//ontology/Ontology"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="classes" upperBound="-1"
          eType="#//ontology/OntologyClass" containment="true" resolveProxies="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="classHierarchy" lowerBound="1"
          eType="#//ontology/OntologyClass"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="individuals" upperBound="-1"
          eType="#//ontology/OntologyIndividual" containment="true" resolveProxies="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="objectPropertyHierarchy"
          lowerBound="1" eType="#//ontology/OntologyObjectProperty"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="objectProperties" upperBound="-1"
          eType="#//ontology/OntologyObjectProperty" containment="true" resolveProxies="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="annotationProperties"
          upperBound="-1" eType="#//ontology/OntologyAnnotationProperty" containment="true"
          resolveProxies="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="nrOfClasses" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="nrOfIndividuals" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="nrOfObjectProperties"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ontologyFile" eType="#//ontologyMgr/OntologyFile"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OntologyNamespace" eSuperTypes="#//ontology/OntologyEntity"/>
    <eClassifiers xsi:type="ecore:EClass" name="OntologyEntity" eSuperTypes="#//ontology/OntologyItem">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="prefix" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="annotations" upperBound="-1"
          eType="#//ontology/OntologyAnnotation" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OntologyClass" eSuperTypes="#//ontology/OntologyEntity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="individuals" upperBound="-1"
          eType="#//ontology/OntologyIndividual"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="superClasses" upperBound="-1"
          eType="#//ontology/OntologyClass"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subClasses" upperBound="-1"
          eType="#//ontology/OntologyClass"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OntologyIndividual" eSuperTypes="#//ontology/OntologyEntity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
          eType="#//ontology/OntologyClass"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="objectPropertyAssertions"
          upperBound="-1" eType="#//ontology/OntologyObjectPropertyAssertion"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OntologyObjectProperty" eSuperTypes="#//ontology/OntologyEntity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="superObjectProperties"
          upperBound="-1" eType="#//ontology/OntologyObjectProperty"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subObjectProperties"
          upperBound="-1" eType="#//ontology/OntologyObjectProperty"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="inverseObjectProperties"
          upperBound="-1" eType="#//ontology/OntologyObjectProperty"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="range" eType="#//ontology/OntologyClass"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="domain" eType="#//ontology/OntologyClass"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="functional" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="inverseFunctional" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="transitive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="symmetric" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="asymmetric" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="reflexive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="irreflexive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OntologyObjectPropertyAssertion" eSuperTypes="#//ontology/OntologyItem">
      <eStructuralFeatures xsi:type="ecore:EReference" name="objectProperty" lowerBound="1"
          eType="#//ontology/OntologyObjectProperty"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="object" lowerBound="1"
          eType="#//ontology/OntologyIndividual"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OntologyAnnotationProperty" eSuperTypes="#//ontology/OntologyEntity"/>
    <eClassifiers xsi:type="ecore:EClass" name="OntologyAnnotation" eSuperTypes="#//ontology/OntologyItem">
      <eStructuralFeatures xsi:type="ecore:EReference" name="annotationproperty" eType="#//ontology/OntologyAnnotationProperty"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
