<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="oida" nsURI="http://net/bauhaus-luftfahrt/oida" nsPrefix="net.bauhaus-luftfahrt.oida">
  <eSubpackages name="ontologyMgr" nsURI="http://net/bauhaus-luftfahrt/oida/ontologyMgr"
      nsPrefix="net.bauhaus-luftfahrt.oida.ontologyMgr">
    <eClassifiers xsi:type="ecore:EClass" name="Library">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="owner" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="creationDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ontologies" upperBound="-1"
          eType="#//ontologyMgr/LocalReferenceOntologyFileSet" containment="true"
          resolveProxies="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="referenceOntology" eType="#//ontologyMgr/LocalReferenceOntologyFileSet"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LocalReferenceOntologyFileSet" eSuperTypes="#//ontologyMgr/OntologyFile">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="maintenanceFileName"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="GitRepoOntologyEntry" eSuperTypes="#//ontologyMgr/LocalReferenceOntologyFileSet">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="repoURL" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="gitUsername" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="gitPassword" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OntologyFile">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="managedOntology" eType="#//ontology/Ontology"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="ontology" nsURI="http://net/bauhaus-luftfahrt/oida/ontology"
      nsPrefix="net.bauhaus-luftfahrt.oida.ontology">
    <eClassifiers xsi:type="ecore:EClass" name="OntologyClass" eSuperTypes="#//ontology/OntologyEntity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="individuals" upperBound="-1"
          eType="#//ontology/OntologyIndividual"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="superClasses" upperBound="-1"
          eType="#//ontology/OntologyClass"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subClasses" upperBound="-1"
          eType="#//ontology/OntologyClass"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OntologyEntity" eSuperTypes="#//ontology/OntologyItem">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="prefix" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="containingOntology" eType="#//ontology/Ontology"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Ontology" eSuperTypes="#//ontology/OntologyItem">
      <eStructuralFeatures xsi:type="ecore:EReference" name="includes" upperBound="-1"
          eType="#//ontology/Ontology" containment="true" resolveProxies="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="classes" upperBound="-1"
          eType="#//ontology/OntologyClass" containment="true" resolveProxies="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="individuals" upperBound="-1"
          eType="#//ontology/OntologyIndividual" containment="true" resolveProxies="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="nrOfClasses" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="nrOfIndividuals" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ontologyEntry" eType="#//ontologyMgr/OntologyFile"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OntologyIndividual" eSuperTypes="#//ontology/OntologyEntity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
          eType="#//ontology/OntologyClass"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OntologyItem">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
