<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mapping" nsURI="http://oida/transformation/mapping" nsPrefix="oida.merge">
  <eClassifiers xsi:type="ecore:EClass" name="ReferenceMapping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceEObject" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceEObject" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eClassMapping" eType="#//EClassMapping"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EClassMapping">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referenceEClass" eType="#//EClass"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referneceIndividual" eType="#//Individual"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeMappings" upperBound="-1"
        eType="#//AttributeMapping"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Individual" instanceClassName="org.apache.jena.ontology.Individual"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EClass" instanceClassName="org.eclipse.emf.ecore.EClass"/>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeMapping">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceEAttribute" eType="#//EAttribute"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referenceEAttribute" eType="#//EAttribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EAttribute" instanceClassName="org.eclipse.emf.ecore.EAttribute"/>
</ecore:EPackage>
