<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="reference"
    nsURI="http://bhl.net/cdt/reference" nsPrefix="net.bhl.cdt.reference">
  <eClassifiers xsi:type="ecore:EClass" name="Component" eSuperTypes="#//ModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="#//ModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Quantity" eSuperTypes="#//Parameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="Angle" eSuperTypes="#//Quantity"/>
  <eClassifiers xsi:type="ecore:EClass" name="Area" eSuperTypes="#//Quantity"/>
  <eClassifiers xsi:type="ecore:EClass" name="Counter" eSuperTypes="#//Quantity"/>
  <eClassifiers xsi:type="ecore:EClass" name="CounterOfComponents" eSuperTypes="#//Counter"/>
  <eClassifiers xsi:type="ecore:EClass" name="CounterOfPersons" eSuperTypes="#//Counter"/>
  <eClassifiers xsi:type="ecore:EClass" name="Density" eSuperTypes="#//Quantity"/>
  <eClassifiers xsi:type="ecore:EClass" name="Length" eSuperTypes="#//Quantity"/>
  <eClassifiers xsi:type="ecore:EClass" name="Mass" eSuperTypes="#//Quantity"/>
  <eClassifiers xsi:type="ecore:EClass" name="Ratio" eSuperTypes="#//Quantity"/>
  <eClassifiers xsi:type="ecore:EClass" name="Volume" eSuperTypes="#//Quantity"/>
  <eClassifiers xsi:type="ecore:EClass" name="LiquidVolume" eSuperTypes="#//Volume"/>
  <eClassifiers xsi:type="ecore:EClass" name="ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
