<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="matcher"
    nsURI="http://bhl.net/cdt/ontology/matcher" nsPrefix="net.bhl.cdt.ontology">
  <eClassifiers xsi:type="ecore:EClass" name="MatchRecommendation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" eType="#//OntResource"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="target" eType="#//OntResource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="OntResource" instanceClassName="com.hp.hpl.jena.ontology.OntResource"/>
  <eClassifiers xsi:type="ecore:EClass" name="ManualMatch" eSuperTypes="#//MatchRecommendation"/>
</ecore:EPackage>
