<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="w3c" nsURI="http://www.bauhaus-luftfahrt.net/w3c" nsPrefix="w3c">
  <eClassifiers xsi:type="ecore:EClass" name="IIdentifyableObject" abstract="true"
      interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eSubpackages name="rdfs" nsURI="http://www.bauhaus-luftfahrt.net/w3c/rdfs" nsPrefix="rdfs">
    <eClassifiers xsi:type="ecore:EClass" name="Resource"/>
    <eClassifiers xsi:type="ecore:EClass" name="Class" eSuperTypes="#//rdfs/Resource"/>
    <eClassifiers xsi:type="ecore:EClass" name="Literal" eSuperTypes="#//rdfs/Resource"/>
    <eClassifiers xsi:type="ecore:EClass" name="DataType" eSuperTypes="#//rdfs/Class"/>
    <eClassifiers xsi:type="ecore:EClass" name="ConstraintProperty"/>
  </eSubpackages>
  <eSubpackages name="owl" nsURI="http://www.bauhaus-luftfahrt.net/w3c/owl" nsPrefix="owl">
    <eClassifiers xsi:type="ecore:EClass" name="OWLOntology" eSuperTypes="#//IIdentifyableObject">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ontologyAnnotations"
          upperBound="-1" eType="#//owl/OWLAnnotation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
          eType="#//owl/OWLOntology"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="directlyImports" upperBound="-1"
          eType="#//owl/OWLOntology"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="versionIRI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="axioms" upperBound="-1"
          eType="#//owl/OWLAxiom"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OWLAnnotation">
      <eStructuralFeatures xsi:type="ecore:EReference" name="annotationAnnotations"
          upperBound="-1" eType="#//owl/OWLAnnotation"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OWLAxiom">
      <eStructuralFeatures xsi:type="ecore:EReference" name="axiomAnnotations" upperBound="-1"
          eType="#//owl/OWLAnnotation"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OWLEntity" eSuperTypes="#//IIdentifyableObject"/>
    <eClassifiers xsi:type="ecore:EClass" name="OWLClassExpression"/>
    <eClassifiers xsi:type="ecore:EClass" name="OWLClass" eSuperTypes="#//owl/OWLEntity #//owl/OWLClassExpression"/>
    <eClassifiers xsi:type="ecore:EClass" name="OWLObjectProperty" eSuperTypes="#//owl/OWLEntity"/>
    <eClassifiers xsi:type="ecore:EClass" name="OWLDataProperty" eSuperTypes="#//owl/OWLEntity"/>
    <eClassifiers xsi:type="ecore:EClass" name="OWLAnnotationProperty" eSuperTypes="#//owl/OWLEntity"/>
    <eClassifiers xsi:type="ecore:EClass" name="OWLDataRange"/>
    <eClassifiers xsi:type="ecore:EClass" name="OWLDataType" eSuperTypes="#//owl/OWLEntity #//owl/OWLDataRange"/>
    <eClassifiers xsi:type="ecore:EClass" name="OWLIndividual"/>
    <eClassifiers xsi:type="ecore:EClass" name="OWLNamedIndividual" eSuperTypes="#//owl/OWLEntity #//owl/OWLIndividual"/>
    <eClassifiers xsi:type="ecore:EClass" name="OWLAnonymousIndividual" eSuperTypes="#//owl/OWLIndividual"/>
    <eClassifiers xsi:type="ecore:EClass" name="OWLLiteral"/>
  </eSubpackages>
</ecore:EPackage>
